/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FornecedorDto } from './fornecedorDto';
import { GrupoProdutoDto } from './grupoProdutoDto';


export interface ProdutoDto { 
    fornecedorDto?: FornecedorDto;
    grupoProdutoDto?: GrupoProdutoDto;
    procod?: number;
    procusto?: number;
    proestm?: number;
    proestoque?: number;
    pronome?: string;
    propreco?: number;
    prostatus?: string;
}
